// Read-only tests: local production bundle uses real catalog data; guest signup is blocked.
// Set CATALOG_TEST_BASE_URL to check the deployed frontend after release.
﻿import fs from 'node:fs/promises';import path from 'node:path';import {spawn} from 'node:child_process';import {createServer} from 'node:http';import assert from 'node:assert/strict';
const root=path.resolve('dist'),out=path.resolve('.tmp/live-menu-browser');await fs.mkdir(out,{recursive:true});const profile=await fs.mkdtemp(path.resolve('.tmp/live-menu-profile-'));
const server=createServer(async(req,res)=>{try{const file=path.resolve(root,'.'+(req.url==='/'?'/index.html':new URL(req.url,'http://localhost').pathname));if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml','.png':'image/png','.jpg':'image/jpeg','.ttf':'font/ttf'})[path.extname(file)]??'application/octet-stream');res.end(await fs.readFile(file));}catch{res.writeHead(404).end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));
const child=spawn('C:/Program Files/Google/Chrome/Application/chrome.exe',['--headless=new','--no-sandbox','--disable-gpu','--disable-crash-reporter','--no-first-run','--force-prefers-reduced-motion','--remote-debugging-port=0',`--user-data-dir=${profile}`],{windowsHide:true,stdio:'ignore'});
let socket;const pending=new Map();let seq=0;const wait=ms=>new Promise(r=>setTimeout(r,ms));
try{let port;for(let i=0;i<100;i++){try{port=(await fs.readFile(path.join(profile,'DevToolsActivePort'),'utf8')).split('\n')[0];break;}catch{await wait(100);}}assert(port,'Chrome debugger did not start');const tabs=await(await fetch(`http://127.0.0.1:${port}/json`,{signal:AbortSignal.timeout(10000)})).json();socket=new WebSocket(tabs.find(t=>t.type==='page').webSocketDebuggerUrl);await new Promise((r,j)=>{socket.onopen=r;socket.onerror=j;});socket.onmessage=e=>{const m=JSON.parse(e.data);if(m.id){const p=pending.get(m.id);pending.delete(m.id);m.error?p.reject(Error(JSON.stringify(m.error))):p.resolve(m.result);}};const command=(method,params={})=>new Promise((resolve,reject)=>{const id=++seq;pending.set(id,{resolve,reject});socket.send(JSON.stringify({id,method,params}));});
await command('Page.enable');await command('Page.addScriptToEvaluateOnNewDocument',{source:`localStorage.setItem('yemunnai-intro-seen','true');const original=window.fetch;window.fetch=async(resource,options={})=>{const u=typeof resource==='string'?resource:resource.url;if(u.includes('/auth/v1/signup'))return new Response(JSON.stringify({message:'Guest signup excluded from read-only catalog test'}),{status:503,headers:{'Content-Type':'application/json'}});if(window.__menuBlocked&&u.includes('/rest/v1/food_items'))throw TypeError('Simulated offline menu');return original(resource,options);};`});
const exercise=async function(width){const pause=ms=>new Promise(r=>setTimeout(r,ms));const until=async(f,label)=>{for(let i=0;i<300;i++){if(f())return;await pause(50);}throw Error(label);};const check=(v,label)=>{if(!v)throw Error(label);};const visible=e=>e&&e.getClientRects().length>0&&!e.closest('[aria-hidden=true]');const buttons=()=>[...document.querySelectorAll('button')].filter(visible);const button=label=>buttons().find(e=>e.textContent.trim()===label);const cards=()=>[...document.querySelectorAll('.food-card:not(.food-skeleton)')].filter(visible);const input=(e,value)=>{Object.getOwnPropertyDescriptor(Object.getPrototypeOf(e),'value').set.call(e,value);e.dispatchEvent(new Event('input',{bubbles:true}));};
await until(()=>cards().length>0,'Real menu did not load');check(![...document.querySelectorAll('[role=alert]')].filter(visible).some(e=>e.textContent.includes('Unable to load')),'Menu error visible');const initial=cards().length;check(initial>=20,'Expected production dishes');check(document.documentElement.scrollWidth<=innerWidth,'Horizontal overflow');const shell=document.querySelector('.app-viewport').getBoundingClientRect();check(Math.abs(shell.width-(width<=600?width:480))<1,'Mobile shell does not fill expected width');
const dock=document.querySelector('.buyer-dock');const dockBox=dock.getBoundingClientRect();check(dockBox.left>=0&&dockBox.right<=innerWidth&&dockBox.bottom<=innerHeight+1,'Dock outside viewport');const tabs=[...dock.querySelectorAll('[role=tab]')];check(tabs.length===3&&tabs.every(e=>e.querySelector('svg')&&e.getBoundingClientRect().height>=44),'Three icon tabs with touch targets required');check(tabs.filter(e=>e.getAttribute('aria-selected')==='true').length===1,'One selected tab required');tabs[0].focus();tabs[0].dispatchEvent(new KeyboardEvent('keydown',{key:'ArrowRight',bubbles:true}));await until(()=>document.querySelector('#buyer-panel-saved')&&tabs[1].getAttribute('aria-selected')==='true','Arrow key must activate Saved');check(document.activeElement===tabs[1],'Keyboard focus must follow tab');tabs[1].dispatchEvent(new KeyboardEvent('keydown',{key:'End',bubbles:true}));await until(()=>document.querySelector('#buyer-panel-orders'),'End key must activate Orders');tabs[2].dispatchEvent(new KeyboardEvent('keydown',{key:'Home',bubbles:true}));await until(()=>cards().length===initial&&document.querySelector('#buyer-panel-discover'),'Home key must restore Discover');const language=dock.querySelector('select');Object.getOwnPropertyDescriptor(HTMLSelectElement.prototype,'value').set.call(language,'te');language.dispatchEvent(new Event('change',{bubbles:true}));await until(()=>tabs[0].textContent.match(/[\u0C00-\u0C7F]/),'Telugu tab labels must update');Object.getOwnPropertyDescriptor(HTMLSelectElement.prototype,'value').set.call(language,'en');language.dispatchEvent(new Event('change',{bubbles:true}));await until(()=>button('Discover'),'English tab labels must restore');window.scrollTo(0,document.documentElement.scrollHeight);await pause(80);check(cards().at(-1).getBoundingClientRect().bottom<=dock.getBoundingClientRect().top,'Dock covers final dish');window.scrollTo(0,0);
const search=document.querySelector('input[aria-label="Search food or shops"]');input(search,'zz-no-matching-food-zz');await until(()=>cards().length===0&&document.body.textContent.includes('No dishes found'),'Empty search must show zero dishes');check(!document.querySelector('[data-svg-visual=home]'),'Empty search must not show sample SVG food');button('Clear filters').click();await until(()=>cards().length===initial,'Clear filters must restore menu');
const searchTerm=cards()[0].querySelector('h3').textContent;input(search,searchTerm);await until(()=>cards().length>0&&cards().every(e=>e.querySelector('h3').textContent.toLowerCase().includes(searchTerm.toLowerCase())),'Search did not filter dishes');document.querySelector('button[aria-label="Clear search"]').click();await until(()=>cards().length===initial,'Clear search did not restore');
const packed=buttons().find(e=>e.textContent.startsWith('Packed foods'));packed.click();await until(()=>cards().length>0&&cards().length<initial,'Packed category did not filter');buttons().find(e=>e.textContent.startsWith('Cooked foods')).click();await until(()=>cards().length===initial,'Cooked category did not restore');
input(document.querySelector('[aria-label="Maximum price"]'),'20');await until(()=>cards().length>0&&cards().every(e=>Number(e.querySelector('.food-price')?.textContent.replace(/[^\d]/g,''))<=20),'Price filter incorrect');input(document.querySelector('[aria-label="Maximum price"]'),'');await until(()=>cards().length===initial,'Price clear failed');
const veg=document.querySelector('.veg-filter input');veg.click();await until(()=>cards().length===0,'Unknown dietary information must not be labelled vegetarian');check(!document.querySelector('[data-svg-visual=home]'),'Veg empty state cannot show sample dishes');veg.click();await until(()=>cards().length===initial,'Veg toggle restore failed');
const save=cards()[0].querySelector('.food-save');const name=cards()[0].querySelector('h3').textContent;save.click();button('Saved').click();await until(()=>cards().length===1&&cards()[0].querySelector('h3').textContent===name,'Saved selection incorrect');cards()[0].querySelector('.food-save').click();await until(()=>cards().length===0&&document.body.textContent.includes('No saved dishes yet'),'Removing Saved must show empty state');button('Discover').click();await until(()=>cards().length===initial,'Discover restore failed');
const orderCard=cards().find(e=>e.querySelector('.food-action').textContent.startsWith('Order')&&!e.querySelector('.food-action').disabled);const detailCard=orderCard??cards()[0];const selected=detailCard.querySelector('h3').textContent;const price=Number(detailCard.querySelector('.food-price').textContent.replace(/[^\d]/g,''));detailCard.querySelector('.food-photo-open').click();await until(()=>[...document.querySelectorAll('.detail-screen h1')].filter(visible).some(e=>e.textContent===selected),'Detail must show actual dish');check([...document.querySelectorAll('.detail-screen strong')].filter(visible)[0].textContent==='₹'+price,'Detail price incorrect');button('Back').click();await until(()=>cards().length===initial,'Back must restore menu');
if(orderCard){const same=cards().find(e=>e.querySelector('h3').textContent===selected);same.querySelector('.food-action').click();await until(()=>document.querySelector('[data-svg-visual=checkout]')?.querySelector('button[aria-label="Increase value"]'),'Checkout controls missing');const dialog=document.querySelector('[data-svg-visual=checkout]');check(dialog.textContent.includes(selected),'Checkout selected item incorrect');dialog.querySelector('[aria-label="Increase value"]').click();await until(()=>document.querySelector('[data-svg-visual=checkout]')?.querySelector('button[aria-label="Confirm order · ₹'+price*2+'"]'),'Checkout quantity/total incorrect');document.querySelector('[data-svg-visual=checkout] button[aria-label="Close checkout"]').click();await until(()=>!document.querySelector('[data-svg-visual=checkout]'),'Checkout close failed');}else{check(!cards().some(e=>e.querySelector('.food-action').textContent.startsWith('Order')&&!e.querySelector('.food-action').disabled),'Closed/unavailable dishes cannot start orders');}
const walkCard=cards().find(e=>e.querySelector('.food-action').textContent.trim()==='Walk In');check(walkCard,'An open walk-in dish is expected');const walkVendor=walkCard.closest('.discovery-group').querySelector('h2').textContent;walkCard.querySelector('.food-action').click();await until(()=>[...document.querySelectorAll('[role=dialog]')].filter(visible).some(e=>e.textContent.includes(walkVendor)),'Map must show actual selected vendor');const map=[...document.querySelectorAll('[role=dialog]')].filter(visible)[0];const mapsButton=buttons().find(e=>e.textContent.trim()==='Open in Google Maps');check(mapsButton&&mapsButton.getBoundingClientRect().bottom<=innerHeight,'Map action must stay in view');window.open=url=>{window.__mapsTarget=url;};mapsButton.click();check(window.__mapsTarget?.startsWith('https://www.google.com/maps/'),'Maps action must open Google Maps');Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async()=>{throw Error('denied');}}});button('Copy').click();await until(()=>[...document.querySelectorAll('[role=alert]')].filter(visible).some(e=>e.textContent.includes('Could not copy')),'Copy failure must not claim success');Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async text=>{window.__copiedAddress=text;}}});button('Copy').click();await until(()=>button('Copied!'),'Copy success must be confirmed');check(window.__copiedAddress.includes(walkVendor),'Copied address must match selected vendor');buttons().find(e=>e.getAttribute('aria-label')==='Close').click();await until(()=>![...document.querySelectorAll('[role=dialog]')].filter(visible).length,'Map must close');
window.__menuBlocked=true;window.dispatchEvent(new Event('online'));await until(()=>[...document.querySelectorAll('[role=alert]')].filter(visible).some(e=>e.textContent.includes('Unable to load')),'Offline warning absent');check(!document.querySelector('.empty-menu'),'Network failure is not an empty catalog');check(cards().every(e=>e.querySelector('.food-action').disabled),'Stale menu ordering must be disabled');window.__menuBlocked=false;button('Retry').click();await until(()=>cards().length===initial&&![...document.querySelectorAll('[role=alert]')].filter(visible).some(e=>e.textContent.includes('Unable to load')),'Retry did not recover menu');
return {width,viewport:innerWidth,cards:initial,shellWidth:shell.width,checks:['dock bounds/icons/44px targets','selected tab/keyboard arrows/Home/End','English/Telugu navigation','last dish clear of dock','real production menu','responsive width','search/no results/reset','categories','price filter','unknown diet filter','Saved add/remove','live detail/back',orderCard?'checkout quantity/price/close':'no orders from closed or unavailable shops','map vendor/footer/Google Maps/copy failure+success/close','network failure/disabled stale actions/retry']};};
const results=[];for(const width of [320,390,469,1280]){await command('Emulation.setDeviceMetricsOverride',{width,height:844,deviceScaleFactor:1,mobile:width<=600});await command('Page.navigate',{url:process.env.CATALOG_TEST_BASE_URL??`http://127.0.0.1:${server.address().port}/`});await wait(400);const result=await command('Runtime.evaluate',{expression:`(${exercise.toString()})(${width})`,awaitPromise:true,returnByValue:true});if(result.exceptionDetails)throw Error(JSON.stringify(result.exceptionDetails));results.push(result.result.value);const png=await command('Page.captureScreenshot',{format:'png'});await fs.writeFile(path.join(out,`menu-${width}.png`),Buffer.from(png.data,'base64'));console.log('PASS',width,result.result.value.cards,'real dishes');}
await fs.writeFile(path.join(out,'results.json'),JSON.stringify(results,null,2));
}finally{socket?.close();child.kill();await wait(500);await new Promise(r=>server.close(r));assert.equal(path.dirname(profile),path.resolve('.tmp'));assert(path.basename(profile).startsWith('live-menu-profile-'));await fs.rm(profile,{recursive:true,force:true,maxRetries:3}).catch(()=>{});}


