import assert from 'node:assert/strict';
import {handleAdmin} from '../supabase/functions/admin-portal/handler.mjs';
const actor='10000000-0000-4000-8000-000000000001',vendor='a0000000-0000-4000-8000-000000000001';
const env={url:'https://fixture.invalid',serviceKey:'private-server-key'};
const request=body=>new Request(env.url,{method:'POST',headers:{Authorization:'Bearer verified-user','Content-Type':'application/json'},body:JSON.stringify(body)});
const run=async(body,{anonymous=false,member=true,error=false}={})=>{
  const calls=[];
  const fetcher=async(url,options)=>{
    calls.push({url,options});
    if(url.endsWith('/auth/v1/user'))return Response.json({id:actor,is_anonymous:anonymous,user_metadata:{admin:true}});
    if(url.includes('/app_admins?'))return Response.json(member?[{user_id:actor}]:[]);
    if(url.includes('/admin/users'))return Response.json({id:crypto.randomUUID()});
    assert.ok(url.includes('/rpc/'));assert.equal(options.headers.Authorization,`Bearer ${env.serviceKey}`);
    assert.equal(JSON.parse(options.body).p_actor,actor,'Actor always comes from verified Auth');
    return Response.json(error?{error:'duplicate_name'}:{success:true});
  };
  return{response:await handleAdmin(request(body),env,fetcher),calls};
};
assert.equal((await run({action:'snapshot'},{anonymous:true})).response.status,403);
assert.equal((await run({action:'snapshot'},{member:false})).response.status,403,'Editable user_metadata cannot grant admin access');
assert.equal((await run({action:'snapshot',p_actor:vendor})).response.status,200);
const business={name:'Test restaurant',image_url:'/images/NewLogo.svg',is_active:true,is_online:false,latitude:null,longitude:null,location_landmark:''};
assert.equal((await run({action:'vendor_save',vendor:business,pin:'1234'},{member:false})).calls.length,2,'No owner accounts created before authorization');
assert.equal((await run({action:'vendor_save',vendor:business,pin:'bad'})).response.status,400);
assert.equal((await run({action:'vendor_save',vendor:{...business,latitude:12},pin:'1234'})).response.status,400,'Coordinates must be a complete pair');
assert.equal((await run({action:'vendor_save',vendor:{...business,image_url:'javascript:alert(1)'},pin:'1234'})).response.status,400);
const created=await run({action:'vendor_save',vendor:business,pin:'1234',ownerId:actor});
assert.equal(created.response.status,200);assert.notEqual(JSON.parse(created.calls.at(-1).options.body).p_input.ownerId,actor,'Owner cannot be supplied by browser');
const rejected=await run({action:'vendor_save',vendor:business,pin:'1234'},{error:true});
assert.equal(rejected.response.status,409);assert.equal(rejected.calls.at(-1).options.method,'DELETE','Unused owner is removed after definitive rejection');
const food={vendor_id:vendor,name:'Dish',price:null,category:'cooked',image_url:null,is_vegetarian:null,in_stock:true,price_variants:[{name:'Medium',price:130,currency:'INR'}]};
assert.equal((await run({action:'food_save',food})).response.status,200);
assert.equal((await run({action:'food_save',food:{...food,price_variants:[{name:'Medium',price:-1,currency:'INR'}]}})).response.status,400);
assert.equal((await run({action:'food_save',food:{...food,price_variants:[...food.price_variants,...food.price_variants]}})).response.status,400);
assert.equal((await run({action:'food_delete',foodId:'invalid'})).response.status,400);
assert.equal((await run({action:'order_transition',orderId:vendor,status:'collected'})).response.status,400,'Collection needs confirmed payment');
assert.equal((await run({action:'telemetry',kind:'page',eventId:crypto.randomUUID(),sessionId:crypto.randomUUID(),route:'/'},{anonymous:true})).response.status,200,'Guest visits do not need admin access');
const unauthorized=await handleAdmin(new Request(env.url,{method:'POST',body:'{}'}),env,()=>{throw Error('Must not call upstream');});
assert.equal(unauthorized.status,401);
const unavailable=await handleAdmin(request({action:'snapshot'}),env,()=>{throw Error('network failure');});assert.equal(unavailable.status,503);
console.log('PASS: admin authorization, spoofing prevention, strict input validation, account cleanup, payment guard, guest telemetry and failure handling.');
